version: 0.2
phases:
  pre_build:
    commands:
      - npm install -g hexo-cli
      - cd src/
      - npm install
  build:
    commands:
      - hexo generate
artifacts:
  files:
    - '**/*'
  base-directory: build